### ISSUE TITLE
TypeError on login

### ISSUE THREAD

**Issue by valmiki** [rohit1290/spam_login_filter#2]
With spam_login_filter version 5.0 activated in elgg 5.0.4, upon attempted login a TypeError is thrown.

The error.log shows:

; PHP message: PHP Fatal error:  Uncaught TypeError: elgg_get_site_entity(): Return value must be of type ElggSite, null re
2023/08/28 10:17:48 [error] 19396#0: *117963 FastCGI sent in stderr: "PHP message: [2023-08-28T10:17:48+02:00] ELGG.CRITICAL: Exception at time 1693210668:
elgg_get_user_by_username(): Argument #1 ($username) must be of type string, null given, called in /Users/[user]/Sites/[mysite]/mod/spam_login_filter/lib/hooks.php on line 136
  {"backtrace":[],"process_id":14372,"memory_peak_usage":"8 MB","memory_usage":"8 MB","url":"/action/login","ip":"198.41.242.74","http_method":"POST","server":"[mysite]","referrer":"https://[mysite]/"}" while reading response header from upstream, client: 198.41.242.74, server: [mysite], request: "POST /action/login HTTP/2.0", upstream: "fastcgi://127.0.0.1:9000", host: "[mysite]", referrer: "https://[mysite]/"
2023/08/28 10:18:00 [error] 19396#0: *117963 FastCGI sent in stderr: "PHP message: [2023-08-28T10:18:00+02:00] ELGG.CRITICAL: Exception at time 1693210680:
elgg_get_user_by_username(): Argument #1 ($username) must be of type string, null given, called in /Users/[user]/Sites/[mysite]/mod/spam_login_filter/lib/hooks.php on line 136

**Comment by rohit1290** [comment]
Hi, it seems like a problem with your elgg setup or server. "elgg_get_site_entity" is an inbuilt core function. If it is returning null then you would have to check your elgg/server as it is not expected to return null. Can you please disable other 3rd party plugins and see if it's working or not? Would it be possible to share the server credentials via message so that I can investigate further? I am not able to replicate this on my end as for me it working absolutely fine on my Elgg 5.x setup.

**Comment by rohit1290** [comment]
Closing the thread as there has been no response for more than a month.
